--- #Create Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: user1-ns

--- #Create Serviceaccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user1-sa
  namespace: user1-ns

--- #Create Secret
apiVersion: v1
kind: Secret
metadata:
  name: user1-secret
  namespace: user1-ns
  annotations:
    kubernetes.io/service-account.name: user1-sa
type: kubernetes.io/service-account-token

--- #Create Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user1-access
  namespace: user1-ns
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

--- #Create Rolebinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user1-access-bind
  namespace:  user1-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user1-access
subjects:
- kind: ServiceAccount
  name: user1-sa
  namespace:  user1-ns

---
apiVersion: v1
kind: LimitRange
metadata:
  name: user1-limit-range
  namespace: user1-ns
spec:
  limits:
  - type: Pod
    min:
      cpu: 100m
    max:
      cpu: 2000m
    min:
      memory: 1Gi
    max:
      memory: 2Gi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: user1-resource-quota
  namespace: user1-ns
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
